# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingWindow(object):
    def setupUi(self, settingWidnow):
        settingWidnow.setObjectName("settingWidnow")
        settingWidnow.resize(619, 794)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(settingWidnow)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(settingWidnow)
        self.groupBox.setMinimumSize(QtCore.QSize(599, 122))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.samp_label = QtWidgets.QLabel(self.groupBox)
        self.samp_label.setMinimumSize(QtCore.QSize(110, 16))
        self.samp_label.setMaximumSize(QtCore.QSize(110, 16))
        self.samp_label.setObjectName("samp_label")
        self.horizontalLayout.addWidget(self.samp_label)
        self.g_sample_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.g_sample_lineEdit.setMinimumSize(QtCore.QSize(160, 0))
        self.g_sample_lineEdit.setObjectName("g_sample_lineEdit")
        self.horizontalLayout.addWidget(self.g_sample_lineEdit)
        self.g_sample_choose = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_sample_choose.sizePolicy().hasHeightForWidth())
        self.g_sample_choose.setSizePolicy(sizePolicy)
        self.g_sample_choose.setMaximumSize(QtCore.QSize(61, 23))
        self.g_sample_choose.setObjectName("g_sample_choose")
        self.horizontalLayout.addWidget(self.g_sample_choose)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ref_label = QtWidgets.QLabel(self.groupBox)
        self.ref_label.setMinimumSize(QtCore.QSize(110, 16))
        self.ref_label.setMaximumSize(QtCore.QSize(111, 16))
        self.ref_label.setObjectName("ref_label")
        self.horizontalLayout_2.addWidget(self.ref_label)
        self.g_ref_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.g_ref_lineEdit.setMinimumSize(QtCore.QSize(160, 0))
        self.g_ref_lineEdit.setObjectName("g_ref_lineEdit")
        self.horizontalLayout_2.addWidget(self.g_ref_lineEdit)
        self.g_ref_choose = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_ref_choose.sizePolicy().hasHeightForWidth())
        self.g_ref_choose.setSizePolicy(sizePolicy)
        self.g_ref_choose.setMaximumSize(QtCore.QSize(61, 23))
        self.g_ref_choose.setObjectName("g_ref_choose")
        self.horizontalLayout_2.addWidget(self.g_ref_choose)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.workin_label = QtWidgets.QLabel(self.groupBox)
        self.workin_label.setMinimumSize(QtCore.QSize(110, 16))
        self.workin_label.setMaximumSize(QtCore.QSize(110, 16))
        self.workin_label.setObjectName("workin_label")
        self.horizontalLayout_3.addWidget(self.workin_label)
        self.g_working_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.g_working_lineEdit.setMinimumSize(QtCore.QSize(160, 0))
        self.g_working_lineEdit.setObjectName("g_working_lineEdit")
        self.horizontalLayout_3.addWidget(self.g_working_lineEdit)
        self.g_working_choose = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_working_choose.sizePolicy().hasHeightForWidth())
        self.g_working_choose.setSizePolicy(sizePolicy)
        self.g_working_choose.setMaximumSize(QtCore.QSize(61, 23))
        self.g_working_choose.setObjectName("g_working_choose")
        self.horizontalLayout_3.addWidget(self.g_working_choose)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(settingWidnow)
        self.groupBox_2.setMinimumSize(QtCore.QSize(599, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(110, 16))
        self.label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.g_counterType = QtWidgets.QComboBox(self.groupBox_2)
        self.g_counterType.setMinimumSize(QtCore.QSize(141, 22))
        self.g_counterType.setMaximumSize(QtCore.QSize(141, 16777215))
        self.g_counterType.setObjectName("g_counterType")
        self.g_counterType.addItem("")
        self.g_counterType.addItem("")
        self.horizontalLayout_4.addWidget(self.g_counterType)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(110, 16))
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.g_com = QtWidgets.QLineEdit(self.groupBox_2)
        self.g_com.setObjectName("g_com")
        self.horizontalLayout_5.addWidget(self.g_com)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(110, 16))
        self.label_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.g_impulses = QtWidgets.QLineEdit(self.groupBox_2)
        self.g_impulses.setObjectName("g_impulses")
        self.horizontalLayout_6.addWidget(self.g_impulses)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(settingWidnow)
        self.groupBox_3.setMinimumSize(QtCore.QSize(290, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.g_defpol = QtWidgets.QTableWidget(self.groupBox_3)
        self.g_defpol.setObjectName("g_defpol")
        self.g_defpol.setColumnCount(2)
        self.g_defpol.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.g_defpol.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Type")
        self.g_defpol.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_7.addWidget(self.g_defpol)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.g_addDefPol = QtWidgets.QPushButton(self.groupBox_3)
        self.g_addDefPol.setMinimumSize(QtCore.QSize(31, 31))
        self.g_addDefPol.setMaximumSize(QtCore.QSize(31, 31))
        self.g_addDefPol.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ikonki/editadd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.g_addDefPol.setIcon(icon)
        self.g_addDefPol.setObjectName("g_addDefPol")
        self.verticalLayout_4.addWidget(self.g_addDefPol)
        self.g_delDefPol = QtWidgets.QPushButton(self.groupBox_3)
        self.g_delDefPol.setMinimumSize(QtCore.QSize(31, 31))
        self.g_delDefPol.setMaximumSize(QtCore.QSize(31, 31))
        self.g_delDefPol.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ikonki/editremove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.g_delDefPol.setIcon(icon1)
        self.g_delDefPol.setObjectName("g_delDefPol")
        self.verticalLayout_4.addWidget(self.g_delDefPol)
        self.g_toHeaders = QtWidgets.QPushButton(self.groupBox_3)
        self.g_toHeaders.setMinimumSize(QtCore.QSize(31, 31))
        self.g_toHeaders.setMaximumSize(QtCore.QSize(31, 31))
        self.g_toHeaders.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ikonki/LEFT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.g_toHeaders.setIcon(icon2)
        self.g_toHeaders.setObjectName("g_toHeaders")
        self.verticalLayout_4.addWidget(self.g_toHeaders)
        self.g_firstDefPol = QtWidgets.QPushButton(self.groupBox_3)
        self.g_firstDefPol.setMinimumSize(QtCore.QSize(31, 31))
        self.g_firstDefPol.setMaximumSize(QtCore.QSize(31, 31))
        self.g_firstDefPol.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ikonki/TOP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.g_firstDefPol.setIcon(icon3)
        self.g_firstDefPol.setObjectName("g_firstDefPol")
        self.verticalLayout_4.addWidget(self.g_firstDefPol)
        self.g_upDefPol = QtWidgets.QPushButton(self.groupBox_3)
        self.g_upDefPol.setMinimumSize(QtCore.QSize(31, 31))
        self.g_upDefPol.setMaximumSize(QtCore.QSize(31, 31))
        self.g_upDefPol.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ikonki/UP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.g_upDefPol.setIcon(icon4)
        self.g_upDefPol.setObjectName("g_upDefPol")
        self.verticalLayout_4.addWidget(self.g_upDefPol)
        self.g_downDefPol = QtWidgets.QPushButton(self.groupBox_3)
        self.g_downDefPol.setMinimumSize(QtCore.QSize(31, 31))
        self.g_downDefPol.setMaximumSize(QtCore.QSize(31, 31))
        self.g_downDefPol.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ikonki/DOWN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.g_downDefPol.setIcon(icon5)
        self.g_downDefPol.setObjectName("g_downDefPol")
        self.verticalLayout_4.addWidget(self.g_downDefPol)
        self.g_lastDefPol = QtWidgets.QPushButton(self.groupBox_3)
        self.g_lastDefPol.setMinimumSize(QtCore.QSize(31, 31))
        self.g_lastDefPol.setMaximumSize(QtCore.QSize(31, 31))
        self.g_lastDefPol.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ikonki/LAST.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.g_lastDefPol.setIcon(icon6)
        self.g_lastDefPol.setObjectName("g_lastDefPol")
        self.verticalLayout_4.addWidget(self.g_lastDefPol)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(settingWidnow)
        self.groupBox_5.setMinimumSize(QtCore.QSize(180, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.g_headers = QtWidgets.QTableWidget(self.groupBox_5)
        self.g_headers.setObjectName("g_headers")
        self.g_headers.setColumnCount(1)
        self.g_headers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.g_headers.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_8.addWidget(self.g_headers)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.g_delHeader = QtWidgets.QPushButton(self.groupBox_5)
        self.g_delHeader.setMinimumSize(QtCore.QSize(31, 31))
        self.g_delHeader.setMaximumSize(QtCore.QSize(31, 31))
        self.g_delHeader.setText("")
        self.g_delHeader.setIcon(icon1)
        self.g_delHeader.setObjectName("g_delHeader")
        self.verticalLayout_5.addWidget(self.g_delHeader)
        self.g_firstHeader = QtWidgets.QPushButton(self.groupBox_5)
        self.g_firstHeader.setMinimumSize(QtCore.QSize(31, 31))
        self.g_firstHeader.setMaximumSize(QtCore.QSize(31, 31))
        self.g_firstHeader.setText("")
        self.g_firstHeader.setIcon(icon3)
        self.g_firstHeader.setObjectName("g_firstHeader")
        self.verticalLayout_5.addWidget(self.g_firstHeader)
        self.g_upHeader = QtWidgets.QPushButton(self.groupBox_5)
        self.g_upHeader.setMinimumSize(QtCore.QSize(31, 31))
        self.g_upHeader.setMaximumSize(QtCore.QSize(31, 31))
        self.g_upHeader.setText("")
        self.g_upHeader.setIcon(icon4)
        self.g_upHeader.setObjectName("g_upHeader")
        self.verticalLayout_5.addWidget(self.g_upHeader)
        self.g_downHeader = QtWidgets.QPushButton(self.groupBox_5)
        self.g_downHeader.setMinimumSize(QtCore.QSize(31, 31))
        self.g_downHeader.setMaximumSize(QtCore.QSize(31, 31))
        self.g_downHeader.setText("")
        self.g_downHeader.setIcon(icon5)
        self.g_downHeader.setObjectName("g_downHeader")
        self.verticalLayout_5.addWidget(self.g_downHeader)
        self.g_lastHeader = QtWidgets.QPushButton(self.groupBox_5)
        self.g_lastHeader.setMinimumSize(QtCore.QSize(31, 31))
        self.g_lastHeader.setMaximumSize(QtCore.QSize(31, 31))
        self.g_lastHeader.setText("")
        self.g_lastHeader.setIcon(icon6)
        self.g_lastHeader.setObjectName("g_lastHeader")
        self.verticalLayout_5.addWidget(self.g_lastHeader)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9.addWidget(self.groupBox_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.g_ok = QtWidgets.QPushButton(settingWidnow)
        self.g_ok.setObjectName("g_ok")
        self.horizontalLayout_10.addWidget(self.g_ok)
        self.g_cancel = QtWidgets.QPushButton(settingWidnow)
        self.g_cancel.setObjectName("g_cancel")
        self.horizontalLayout_10.addWidget(self.g_cancel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)

        self.retranslateUi(settingWidnow)
        self.g_cancel.clicked.connect(settingWidnow.close)
        QtCore.QMetaObject.connectSlotsByName(settingWidnow)

    def retranslateUi(self, settingWidnow):
        _translate = QtCore.QCoreApplication.translate
        settingWidnow.setWindowTitle(_translate("settingWidnow", "Settings Window"))
        self.groupBox.setTitle(_translate("settingWidnow", "Directories"))
        self.samp_label.setText(_translate("settingWidnow", "Samples directory:"))
        self.g_sample_lineEdit.setText(_translate("settingWidnow", "C:\\"))
        self.g_sample_choose.setText(_translate("settingWidnow", "Choose"))
        self.ref_label.setText(_translate("settingWidnow", "References directory:"))
        self.g_ref_lineEdit.setText(_translate("settingWidnow", "C:\\"))
        self.g_ref_choose.setText(_translate("settingWidnow", "Choose"))
        self.workin_label.setText(_translate("settingWidnow", "Working directory:"))
        self.g_working_lineEdit.setText(_translate("settingWidnow", "C:\\"))
        self.g_working_choose.setText(_translate("settingWidnow", "Choose"))
        self.groupBox_2.setTitle(_translate("settingWidnow", "Counter Settings"))
        self.label.setText(_translate("settingWidnow", "Counter type:"))
        self.g_counterType.setItemText(0, _translate("settingWidnow", "wo - WoBIT counter"))
        self.g_counterType.setItemText(1, _translate("settingWidnow", "pi - AGH Counter"))
        self.label_2.setText(_translate("settingWidnow", "COM:"))
        self.g_com.setText(_translate("settingWidnow", "COM3"))
        self.label_3.setText(_translate("settingWidnow", "impulses / mm"))
        self.g_impulses.setText(_translate("settingWidnow", "800"))
        self.groupBox_3.setTitle(_translate("settingWidnow", "Field definitions"))
        item = self.g_defpol.horizontalHeaderItem(0)
        item.setText(_translate("settingWidnow", "Code"))
        self.groupBox_5.setTitle(_translate("settingWidnow", "Header definition"))
        item = self.g_headers.horizontalHeaderItem(0)
        item.setText(_translate("settingWidnow", "Code"))
        self.g_ok.setText(_translate("settingWidnow", "OK"))
        self.g_cancel.setText(_translate("settingWidnow", "Cancel"))
