# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_LDB_measure.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1329, 800)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(401, 76))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 76))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_new_sample = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_new_sample.sizePolicy().hasHeightForWidth())
        self.pushButton_new_sample.setSizePolicy(sizePolicy)
        self.pushButton_new_sample.setMinimumSize(QtCore.QSize(80, 38))
        self.pushButton_new_sample.setObjectName("pushButton_new_sample")
        self.horizontalLayout.addWidget(self.pushButton_new_sample)
        self.pushButton_load_sample = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load_sample.sizePolicy().hasHeightForWidth())
        self.pushButton_load_sample.setSizePolicy(sizePolicy)
        self.pushButton_load_sample.setMinimumSize(QtCore.QSize(100, 38))
        self.pushButton_load_sample.setObjectName("pushButton_load_sample")
        self.horizontalLayout.addWidget(self.pushButton_load_sample)
        self.pushButton_save_sample = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_save_sample.setMinimumSize(QtCore.QSize(100, 38))
        self.pushButton_save_sample.setObjectName("pushButton_save_sample")
        self.horizontalLayout.addWidget(self.pushButton_save_sample)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_format = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_format.setMaximumSize(QtCore.QSize(64, 16777215))
        self.comboBox_format.setObjectName("comboBox_format")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_format)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(301, 76))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 78))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(51, 18))
        self.label_2.setMaximumSize(QtCore.QSize(51, 18))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_cat_means = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_cat_means.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_cat_means.setFont(font)
        self.lineEdit_cat_means.setText("")
        self.lineEdit_cat_means.setObjectName("lineEdit_cat_means")
        self.horizontalLayout_2.addWidget(self.lineEdit_cat_means)
        self.pushButton_choose_dir = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_choose_dir.setMinimumSize(QtCore.QSize(0, 38))
        self.pushButton_choose_dir.setMaximumSize(QtCore.QSize(55, 16777215))
        self.pushButton_choose_dir.setObjectName("pushButton_choose_dir")
        self.horizontalLayout_2.addWidget(self.pushButton_choose_dir)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(101, 20))
        self.label_3.setMaximumSize(QtCore.QSize(101, 20))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_cat_samples = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_cat_samples.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_cat_samples.setFont(font)
        self.lineEdit_cat_samples.setObjectName("lineEdit_cat_samples")
        self.horizontalLayout_2.addWidget(self.lineEdit_cat_samples)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.pushButton_settings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_settings.setMinimumSize(QtCore.QSize(81, 76))
        self.pushButton_settings.setMaximumSize(QtCore.QSize(81, 76))
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.horizontalLayout_5.addWidget(self.pushButton_settings)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_attr = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_attr.setObjectName("tableWidget_attr")
        self.tableWidget_attr.setColumnCount(0)
        self.tableWidget_attr.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget_attr)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(511, 301))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 301))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_meas = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget_meas.setObjectName("tableWidget_meas")
        self.tableWidget_meas.setColumnCount(0)
        self.tableWidget_meas.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_meas)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_new_sequence = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_new_sequence.setMinimumSize(QtCore.QSize(70, 34))
        self.pushButton_new_sequence.setObjectName("pushButton_new_sequence")
        self.horizontalLayout_4.addWidget(self.pushButton_new_sequence)
        self.pushButton_continue_sequence = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_continue_sequence.setMinimumSize(QtCore.QSize(70, 34))
        self.pushButton_continue_sequence.setObjectName("pushButton_continue_sequence")
        self.horizontalLayout_4.addWidget(self.pushButton_continue_sequence)
        self.pushButton_delete_sequence = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_delete_sequence.setMinimumSize(QtCore.QSize(70, 34))
        self.pushButton_delete_sequence.setObjectName("pushButton_delete_sequence")
        self.horizontalLayout_4.addWidget(self.pushButton_delete_sequence)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_cor_selected = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_cor_selected.setMinimumSize(QtCore.QSize(120, 34))
        self.pushButton_cor_selected.setObjectName("pushButton_cor_selected")
        self.horizontalLayout_4.addWidget(self.pushButton_cor_selected)
        self.pushButton_mean_selected = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_mean_selected.setMinimumSize(QtCore.QSize(130, 34))
        self.pushButton_mean_selected.setMaximumSize(QtCore.QSize(151, 34))
        self.pushButton_mean_selected.setObjectName("pushButton_mean_selected")
        self.horizontalLayout_4.addWidget(self.pushButton_mean_selected)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(461, 301))
        self.groupBox_5.setMaximumSize(QtCore.QSize(461, 301))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_read_measure = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_read_measure.setGeometry(QtCore.QRect(10, 30, 341, 101))
        self.pushButton_read_measure.setObjectName("pushButton_read_measure")
        self.textEdit_meas = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_meas.setGeometry(QtCore.QRect(360, 30, 91, 261))
        self.textEdit_meas.setObjectName("textEdit_meas")
        self.pushButton_end_measures = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_end_measures.setGeometry(QtCore.QRect(160, 250, 191, 41))
        self.pushButton_end_measures.setObjectName("pushButton_end_measures")
        self.pushButton_clean = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_clean.setGeometry(QtCore.QRect(10, 273, 51, 21))
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 101, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 41, 18))
        self.label_5.setObjectName("label_5")
        self.lineEdit_sapwood = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_sapwood.setGeometry(QtCore.QRect(60, 160, 61, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_sapwood.setFont(font)
        self.lineEdit_sapwood.setText("")
        self.lineEdit_sapwood.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sapwood.setObjectName("lineEdit_sapwood")
        self.pushButton_sapwood_beg = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_sapwood_beg.setGeometry(QtCore.QRect(10, 200, 111, 34))
        self.pushButton_sapwood_beg.setObjectName("pushButton_sapwood_beg")
        self.pushButton_delete_measure = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_delete_measure.setGeometry(QtCore.QRect(200, 150, 151, 71))
        self.pushButton_delete_measure.setObjectName("pushButton_delete_measure")
        self.horizontalLayout_6.addWidget(self.groupBox_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.widget = MplWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(921, 300))
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LDB_Measures"))
        self.groupBox.setTitle(_translate("MainWindow", "Sample"))
        self.pushButton_new_sample.setText(_translate("MainWindow", "New"))
        self.pushButton_load_sample.setText(_translate("MainWindow", "Load"))
        self.pushButton_save_sample.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "as:"))
        self.comboBox_format.setItemText(0, _translate("MainWindow", "*.fh"))
        self.comboBox_format.setItemText(1, _translate("MainWindow", "*.txt"))
        self.comboBox_format.setItemText(2, _translate("MainWindow", "*.avr"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Places"))
        self.label_2.setText(_translate("MainWindow", "Means:"))
        self.pushButton_choose_dir.setText(_translate("MainWindow", "choose"))
        self.label_3.setText(_translate("MainWindow", "Measurements:"))
        self.pushButton_settings.setText(_translate("MainWindow", "Settings"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Attributes"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Measurements"))
        self.pushButton_new_sequence.setText(_translate("MainWindow", "New"))
        self.pushButton_continue_sequence.setText(_translate("MainWindow", "Continue"))
        self.pushButton_delete_sequence.setText(_translate("MainWindow", "Delete"))
        self.pushButton_cor_selected.setText(_translate("MainWindow", "Crossdate selected"))
        self.pushButton_mean_selected.setText(_translate("MainWindow", "Mean from selected"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Device"))
        self.pushButton_read_measure.setText(_translate("MainWindow", "Read measure"))
        self.pushButton_end_measures.setText(_translate("MainWindow", "End of session"))
        self.pushButton_clean.setText(_translate("MainWindow", "clean"))
        self.label_4.setText(_translate("MainWindow", "Sapwood"))
        self.label_5.setText(_translate("MainWindow", "Begin:"))
        self.pushButton_sapwood_beg.setText(_translate("MainWindow", "enter ring no."))
        self.pushButton_delete_measure.setText(_translate("MainWindow", "Delete last \n"
"measure"))
from mplwidget import MplWidget
