# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_LDB_ccoptions.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogOpt(object):
    def setupUi(self, DialogOpt):
        DialogOpt.setObjectName("DialogOpt")
        DialogOpt.resize(305, 262)
        DialogOpt.setMinimumSize(QtCore.QSize(305, 262))
        DialogOpt.setMaximumSize(QtCore.QSize(305, 262))
        font = QtGui.QFont()
        font.setFamily("Arial")
        DialogOpt.setFont(font)
        DialogOpt.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButton_ok = QtWidgets.QPushButton(DialogOpt)
        self.pushButton_ok.setGeometry(QtCore.QRect(20, 210, 141, 34))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(DialogOpt)
        self.pushButton_cancel.setGeometry(QtCore.QRect(190, 210, 101, 34))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.comboBox_samps = QtWidgets.QComboBox(DialogOpt)
        self.comboBox_samps.setGeometry(QtCore.QRect(30, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.comboBox_samps.setFont(font)
        self.comboBox_samps.setFrame(True)
        self.comboBox_samps.setObjectName("comboBox_samps")
        self.comboBox_samps.addItem("")
        self.comboBox_refs = QtWidgets.QComboBox(DialogOpt)
        self.comboBox_refs.setGeometry(QtCore.QRect(180, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.comboBox_refs.setFont(font)
        self.comboBox_refs.setObjectName("comboBox_refs")
        self.comboBox_refs.addItem("")
        self.comboBox_opt = QtWidgets.QComboBox(DialogOpt)
        self.comboBox_opt.setGeometry(QtCore.QRect(100, 101, 191, 41))
        self.comboBox_opt.setObjectName("comboBox_opt")
        self.comboBox_opt.addItem("")
        self.comboBox_opt.addItem("")
        self.comboBox_opt.addItem("")
        self.horizontalSlider_cors = QtWidgets.QSlider(DialogOpt)
        self.horizontalSlider_cors.setGeometry(QtCore.QRect(149, 160, 141, 20))
        self.horizontalSlider_cors.setMinimum(4)
        self.horizontalSlider_cors.setMaximum(45)
        self.horizontalSlider_cors.setProperty("value", 5)
        self.horizontalSlider_cors.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cors.setObjectName("horizontalSlider_cors")
        self.label = QtWidgets.QLabel(DialogOpt)
        self.label.setGeometry(QtCore.QRect(20, 160, 71, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogOpt)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 58, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogOpt)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 91, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DialogOpt)
        self.label_4.setGeometry(QtCore.QRect(180, 10, 101, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(DialogOpt)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 71, 18))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(DialogOpt)
        self.horizontalSlider_cors.sliderMoved['int'].connect(self.label_2.setNum)
        QtCore.QMetaObject.connectSlotsByName(DialogOpt)

    def retranslateUi(self, DialogOpt):
        _translate = QtCore.QCoreApplication.translate
        DialogOpt.setWindowTitle(_translate("DialogOpt", "Crossdate options"))
        self.pushButton_ok.setText(_translate("DialogOpt", "OK"))
        self.pushButton_cancel.setText(_translate("DialogOpt", "Cancel"))
        self.comboBox_samps.setItemText(0, _translate("DialogOpt", "---"))
        self.comboBox_refs.setItemText(0, _translate("DialogOpt", "---"))
        self.comboBox_opt.setItemText(0, _translate("DialogOpt", "All Samples & Reference"))
        self.comboBox_opt.setItemText(1, _translate("DialogOpt", "Sample & All Reference"))
        self.comboBox_opt.setItemText(2, _translate("DialogOpt", "Sample & Reference"))
        self.label.setText(_translate("DialogOpt", "Results:"))
        self.label_2.setText(_translate("DialogOpt", "5"))
        self.label_3.setText(_translate("DialogOpt", "Sample Stack"))
        self.label_4.setText(_translate("DialogOpt", "Reference Stack"))
        self.label_5.setText(_translate("DialogOpt", "Grouping:"))
